### ISSUE TITLE
Port Web STOMP examples to Web MQTT

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-web-mqtt#1]
Just as a way for us to sanity check the plugin and its compatibility with JavaScript client libraries.

**Comment by essen** [comment]
Pushed something at https://github.com/rabbitmq/rabbitmq-web-mqtt-examples

I do not see a way to do temporary queues with the MQTT client, at least nothing involving a reply-to header or similar. So I left out this example for the moment. The normal text example and the bunny are however working.

I did not add the license for the client. It seems to be dual licensed (eclipse public/distribution licenses) and I'm not sure what to do about that.

Otherwise works well enough that I can remove the example from the Web-MQTT repo itself.

Note that I did not test over SSL yet. I will later today or tomorrow morning.

**Comment by essen** [comment]
I have removed the example from this repo. All that's left is testing over SSL.

**Comment by essen** [comment]
Should be good.

**Comment by michaelklishin** [comment]
Thank you. I'll close this, QA the examples repo and perhaps ask for user feedback (as in, announce).
