### ISSUE TITLE
Websocket path as config

### ISSUE THREAD

**Issue by lrodorigo** [rabbitmq/rabbitmq-web-mqtt#21]
Hi all, thanks for wonderful plugin.
A little question:
there's a way to config the default `/ws` path for the web-socket endpoint? 

eg. put the `/` root as endpoint (which is default for the mosquitto websocket implementation), so `ws://server:port/ `is directly the right endpoint, instead of `ws://server:port/ws`

Regards
Luigi

**Comment by lukebakken** [comment]
Thank you for your interest in RabbitMQ.

FYI, this question is more suited to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list rather than a GitHub issue.

As you [can see here](https://github.com/rabbitmq/rabbitmq-web-mqtt/blob/master/src/rabbit_web_mqtt_app.erl#L50-L52), `/ws` is hard-coded at this point.

**Comment by michaelklishin** [comment]
The path is configurable as of #30.
