### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by axwell** [rabbitmq/rabbitmq-web-mqtt#37]
Hello it seems that i can't install the plugin.

rabbitmq-plugins enable rabbitmq_web_mqtt
Error: The following plugins could not be found:
rabbitmq_web_mqtt

I'm running RabbitMQ 3.6.6, Erlang 19.2.1 on Raspian

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin doesn't ship with RabbitMQ in 3.6.6. 3.6.6 is 10 patches behind even in the [now unsupported](http://www.rabbitmq.com/changelog.html) 3.6.x series. Web MQTT should be included into 3.6.16. Please [upgrade](http://www.rabbitmq.com/upgrade.html).
