### ISSUE TITLE
How to make the plugin listen to ipv6？

### ISSUE THREAD

**Issue by Wesure6** [rabbitmq/rabbitmq-web-mqtt#38]
![2018-11-06_192422](https://user-images.githubusercontent.com/18010406/48061376-a79d2480-e1f9-11e8-99e0-da15e79eeaff.png)

only the port 1883 is listen to ipv6

how to config ？ let the port 15675 listen to ipv6

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Apparently this is not covered very well in the [Web MQTT docs](https://www.rabbitmq.com/web-mqtt.html) for 3.7.8 but I think we expanded that guide for 3.7.9. You have the [`web_mqtt.tcp.ip` configuration key](https://github.com/rabbitmq/rabbitmq-web-mqtt/blob/v3.7.8/priv/schema/rabbitmq_web_mqtt.schema#L10), used just like its counterparts in other listeners/protocols that are covered e.g. in [Networking](http://www.rabbitmq.com/networking.html).

I'll make sure by the time 3.7.9 ships this will be covered for Web MQTT and Web STOMP.
